server {
    listen 80;
    
    # Where Nginx should look for my  built files
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        

        try_files $uri $uri/ /index.html; 
    }
}